### ISSUE TITLE
What is a typical num epochs to train savi and ocvpseq?

### ISSUE THREAD

**Issue by RabbitWhite1** [AIS-Bonn/OCVP-object-centric-video-prediction#1]
Hi, may I ask what is a typical num epochs to train savi and ocvpseq for Obj3D and Movia?

**Comment by angelvillar96** [comment]
Hi Zhanghan,


Below you can find the number of iterations (batches) that the modes were trained for, as well as the number of epochs these iterations correspond to. 
Additionally, I report the training time that our experiments took the following using an NVIDIA A6000 with 48Gb

| Dataset | Model | Iters.  | Epochs | Time |
| --- | --- | --- | --- | --- |
| Ojb3D | SAVi | 100k | 2000 | 26h |
|Obj3D | OCVP-Seq | 70k | 1500 | 34h |
|MOVi-A |SAVi | 150k | 2000| 120h |
|MOVi-A | OCVP-Seq | 50k | 300 | 18h |

You can find these numbers and further hyper-parameters in the [configuration files](https://github.com/AIS-Bonn/OCVP-object-centric-video-prediction/tree/master/experiments).
The number of epochs need not match the exact configuration, since the experiments might have been stopped earlier if the model had already converged.

I hope this answers your question.

Do not hesitate to follow up if you still have any questions.

**Comment by RabbitWhite1** [comment]
These numbers are super helpful! Thanks!!
